MOV-AI/data-access-layer

- dal/scopes/flowlinks.py
added cache for flow links so it will be faster with dynamic programming
[^note]:
> cache flowlinks

- dal/models/lock.py
return False if lock release failed
> BP-668 return False if lock failed

- dal/movaidb/utils/robot_info.py
- dal/validation/schema/1.0/Robot.json
Added a utility for getting the robot name and ID from the local Redis DB
Updating the schema for Redis DB to support a new entry Alert in the Robot table
> modifications for supporting the new logging architecture

- dal/classes/protocols/wsredissub.py
- dal/plugins/README.md
added a fix 
because the new aiohttp is changing loop 
we need to check that the current loop is running 
and if not get the new loop 
and only then the task will start
this will fix the bug that the new web socket doesn't start 
because the taks didn't start
jira:
https://movai.atlassian.net/browse/CSAI-2326
'- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue'
[^note]:
> Bugfix/csai 2326/ide does not update

- setup.py
add wildcard in setup.py to movai_core_shared
> fix - adding wildcard to setup.py

- dal/classes/utils/local_robot_info.py
- dal/db_handlers/base_db_handler.py
- dal/db_handlers/time_series_db_handler.py
- dal/models/aclobject.py
- dal/models/baseuser.py
- dal/scopes/fleetrobot.py
jira:
https://movai.atlassian.net/browse/BP-859?atlOrigin=eyJpIjoiNWVmZmZhZTQ4NjU3NDcyZDljY2QzNzQ4Y2ViYzhjOTciLCJwIjoiaiJ9
> Feature bp 859 create alerts handler class for manager dispacher

- dal/scopes/node.py
hot fix for the bug that blocking the pipeline 
where you can't delete node
> fix for the delete node bug

- dal/scopes/node.py
another problem that occurs when trying to delete
> another fix for the node problem

- dal/models/callback.py
Removed the print that spam the log on every added package
> removed the log that print every added package

- dal/scopes/fleetrobot.py
modifications for supporting the new logging architecture (alerts_tool)
[BP-881](https://movai.atlassian.net/browse/BP-881?atlOrigin=eyJpIjoiNDk1OGI2YTg0Y2UyNGExNzgwMWRlZDZlMmQ2YjZkMTgiLCJwIjoiaiJ9)
[BP-881]: https://movai.atlassian.net/browse/BP-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updating fleet_robot to new staructure of alert msg (#91)

- dal/models/nodeinst.py
Another fix for  bp-888 
when flow crash with _launch param
now it have been tested on "test_gd_param_launch.flo"
and it works
> been tested on test_gd_params_launch.flo and works

- dal/models/callback.py
- pyproject.toml
removed all of the debug prints when importing a lib
and set config for black
> removed all debug prints and added config for black

- dal/helpers/parsers.py
Fix for the bug when a param is set on a flow for a subflow
> fix for param in sub flow

- dal/scopes/fleetrobot.py
[BP-649](https://movai.atlassian.net/browse/BP-649?atlOrigin=eyJpIjoiODYzMzJkYzk2Yzc0NGM5MjhjNzYzMjJiMGVkODYxN2IiLCJwIjoiaiJ9)
[BP-649]: https://movai.atlassian.net/browse/BP-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use zmq for metrics create and search

- .flake8
- dal/models/callback.py
- dal/plugins/persistence/filesystem/filesystem.py
- removed huge libs that cause the slowness and probly the bug
- and remoed some bad comments
> created black list with huge libs

- dal/models/nodeinst.py
a fix to push also to the new version
> Bugfix/bp 624/disabled params are going to parameter server

- dal/models/role.py
[BP-905](https://movai.atlassian.net/browse/BP-905)
[BP-905]: https://movai.atlassian.net/browse/BP-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> prevent deleting the role ADMIN

- dal/scopes/fleetrobot.py
Had to remove this code from here and add it to backend due to a circular dependency issue. The issue is related to the importation of vars in fleet robot file. Actually, it was  @erezz-mov-ai that made this suggestion. And it works
> fix robot recovery

- dal/tools/backup.py
DP-1047 : Use redis ping instead of env vars
- Change implementation of fix from #112 
---
> DP-1047 : Use redis ping instead of env vars

- dal/scopes/fleetrobot.py
- dal/tools/backup.py
DP-1047 : Use redis ping instead of env vars
revert robot recovery changes made by @PedroCristovao-Movai
> fix robot recovery and update backup tool

- dal/movaidb/database.py
[BP-926](https://movai.atlassian.net/browse/BP-926)
[BP-926]: https://movai.atlassian.net/browse/BP-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> revert remove delete before set

- dal/db_handlers/time_series_db_handler.py
[BP-942](https://movai.atlassian.net/browse/BP-942) - No logs shown in Fleetboard
[BP-942]: https://movai.atlassian.net/browse/BP-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> No-logs-shown-in-Fleetboard

- .pre-commit-config.yaml
- build-requirements.txt
- dal/tools/backup.py
Fix deprecation warning in backup.py
> Fix deprecation warning in backup.py

- .github/workflows/DeployOnGitRelease.yml
- .github/workflows/DeployOnMergeMain.yml
- .github/workflows/TestOnPR.yml
> cicd : fix permissions

- dal/tools/backup.py
…point (#129)
* Fix missing main() function referenced in setup.py as entrypoint
* review return of backup.py
* Revert backup.py since it brings a bug
---
> Releasing DP-1098

- dal/models/scopestree.py
- [BP-958](https://movai.atlassian.net/browse/BP-958): Task manager - err in generating tasks
[BP-958]: https://movai.atlassian.net/browse/BP-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hotfix BP-958 TaskGenerator

- dal/helpers/parsers.py
- [BP-771](https://movai.atlassian.net/browse/BP-771): Fleet var mentioned on a node parameter is not correctly parsed.
[BP-771]: https://movai.atlassian.net/browse/BP-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> var eval fix

- dal/helpers/parsers.py
- dal/models/scopestree.py
- [BP-771](https://movai.atlassian.net/browse/BP-771): Fleet var mentioned on a node parameter is not correctly parsed.
[BP-771]: https://movai.atlassian.net/browse/BP-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-771 Fleet var

- dal/helpers/parsers.py
- dal/models/scopestree.py
- dal/tools/backup.py
> Release fixes

- .github/CODEOWNERS
- dal/classes/protocols/wsredissub.py
[BP-990](https://movai.atlassian.net/browse/BP-990) - errors on zmq_client
[BP-990]: https://movai.atlassian.net/browse/BP-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-990 - errors on zmq_client

- dal/models/acl.py
- dal/models/role.py
- [BP-998](https://movai.atlassian.net/browse/BP-998): Email notification - adding role
[BP-998]: https://movai.atlassian.net/browse/BP-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-998 added new roles and permissions

- dal/scopes/scope.py
- dal/tools/backup.py
[BP-981](https://movai.atlassian.net/browse/BP-981) - backup tool returns 0 even when removing an non existing file
[BP-981]: https://movai.atlassian.net/browse/BP-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-981 - backup tool returns 0 even when removing an non existing file

- README.md
- dal/models/role.py
- [BP-998](https://movai.atlassian.net/browse/BP-998): Email notification - adding role, by @Mograbi
- [BP-990](https://movai.atlassian.net/browse/BP-990) - errors on zmq_client by @erezz-mov-ai
- [BP-981](https://movai.atlassian.net/browse/BP-981) - backup tool returns 0 even when removing an non existing file by @erezz-mov-ai
- [BP-982](https://movai.atlassian.net/browse/BP-982): Spawner dies and restarts when running a flow, segmentation fault. @Mograbi
[BP-998]: https://movai.atlassian.net/browse/BP-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-990]: https://movai.atlassian.net/browse/BP-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-981]: …
> version 2.4.1.22

- dal/models/acl.py
The permission for the features was rewritten 
now it's fixed
run UI tests to test new fix
or create new user with Admin role
and try to login to the system
> removing rewrite to the apps permission

- dal/models/acl.py
* removing rewrite to the apps permission
new release with an important fix
> removing rewrite to the apps permission (#153)

- dal/classes/protocols/wsredissub.py
- dal/models/acl.py
- dal/models/role.py
Should fix the login problem 
that we create the roles before the apps are updated
so it will update Roles on every restart of the backend when create roles function is called under `user_tool` when creating the default user
In addition update the asyncio function from the deprecated one that relay on loop 
and some more linting
> Bugfix/bp 1032/admin cant login

- dal/classes/protocols/wsredissub.py
- dal/models/role.py
Should fix the login problem
that we create the roles before the apps are updated so it will update Roles on every restart of the backend when create roles function is called under user_tool when creating the default user
In addition update the asyncio function from the deprecated one that relay on loop and some more linting
> Bugfix/bp 1032/admin cant login (#155)

- dal/classes/protocols/wsredissub.py
- dal/models/acl.py
- dal/models/role.py
[BP-1032](https://movai.atlassian.net/browse/BP-1032) - User with admin role can not login to the system
[BP-1032]: https://movai.atlassian.net/browse/BP-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1032 - User with admin role can not login to the system

- dal/models/acl.py
- dal/models/role.py
[BP-1032](https://movai.atlassian.net/browse/BP-1032) - User with admin role can not login to the system
[BP-1032]: https://movai.atlassian.net/browse/BP-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.26

- dal/classes/protocols/wsredissub.py
[BP-1034](https://movai.atlassian.net/browse/BP-1034) - Subscriber to redis returns nothing
[BP-1034]: https://movai.atlassian.net/browse/BP-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1034 - Subscriber to redis returns nothing

- dal/classes/protocols/wsredissub.py
[BP-1034](https://movai.atlassian.net/browse/BP-1034) - Subscriber to redis returns nothing
[BP-1034]: https://movai.atlassian.net/browse/BP-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.28

- dal/classes/protocols/wsredissub.py
[BP-1034](https://movai.atlassian.net/browse/BP-1034) - subscriber to redis returns nothing
[BP-1031](https://movai.atlassian.net/browse/BP-1034) - Connection error Cannot write to closing transport 
[BP-1034]: https://movai.atlassian.net/browse/BP-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1031]: https://movai.atlassian.net/browse/BP-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.29

- dal/helpers/parsers.py
- [BP-1043](https://movai.atlassian.net/browse/BP-1043): Flow stuck during transition
[BP-1043]: https://movai.atlassian.net/browse/BP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1043 fixed issue with regex

- dal/helpers/cache.py
- dal/models/configuration.py
- dal/scopes/configuration.py
- setup.py
- [BP-1053](https://movai.atlassian.net/browse/BP-1053): performance enhancement for Configuration
[BP-1053]: https://movai.atlassian.net/browse/BP-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1053: performance boost

- dal/scopes/configuration.py
- [BP-1063](https://movai.atlassian.net/browse/BP-1063): Configuration parameter changes are not taking any effect
[BP-1063]: https://movai.atlassian.net/browse/BP-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> added caching to Scopes Configuration instead of only Models

- dal/scopes/configuration.py
- [BP-1063](https://movai.atlassian.net/browse/BP-1063): Configuration parameter changes are not taking any effect
[BP-1063]: https://movai.atlassian.net/browse/BP-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1063: fix for None value in Yaml str

- dal/classes/utils/token.py
- dal/models/message.py
[BP-1079](https://movai.atlassian.net/browse/BP-1079) - backend does not start
[BP-1079]: https://movai.atlassian.net/browse/BP-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1079 - backend does not start

- dal/helpers/cache.py
- dal/models/configuration.py
- dal/models/scopestree.py
- [BP-1097](https://movai.atlassian.net/browse/BP-1097): Excessive log Node/Dummy when starting a flow
[BP-1097]: https://movai.atlassian.net/browse/BP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1097: removed  print for the Node/Dummy print

- dal/db_handlers/base_db_handler.py
- setup.py
[BP-984](https://movai.atlassian.net/browse/BP-984) - stream logs from message server to backend
[BP-984]: https://movai.atlassian.net/browse/BP-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.4.1.37

- .bumpversion.cfg
- dal/db_handlers/base_db_handler.py
- setup.py
[BP-984](https://movai.atlassian.net/browse/BP-984) - stream logs from message server to backend
[BP-984]: https://movai.atlassian.net/browse/BP-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.1

- dal/movaidb/database.py
revert the replacing of redis hmset with hset
> hotfix in database.py - returning to hmset

- dal/classes/protocols/wsredissub.py
- dal/models/role.py
- dal/new_models/__init__.py
- dal/new_models/base.py
- dal/new_models/base_model/common.py
- dal/new_models/base_model/redis_model.py
- dal/new_models/robot.py
- dal/new_models/role.py
- dal/tools/migrate_tool.py
[BP-1156](https://movai.atlassian.net/browse/BP-1156) - movai-cli frontend command is failing
[BP-1156]: https://movai.atlassian.net/browse/BP-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1156 - movai-cli frontend command is failing

- dal/classes/protocols/wsredissub.py
- dal/models/role.py
- dal/new_models/__init__.py
- dal/new_models/base.py
- dal/new_models/base_model/common.py
- dal/new_models/base_model/redis_model.py
- dal/new_models/configuration.py
- dal/new_models/flow/flow.py
- dal/new_models/message.py
- dal/new_models/role.py
- dal/new_models/var.py
- dal/tools/backup.py
- dal/tools/migrate_tool.py
- setup.py
[BP-1161](https://movai.atlassian.net/browse/BP-1161) - fix __new__ and __init__ on MovaiBaseModel
[BP-1161]: https://movai.atlassian.net/browse/BP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1161 - fix new and init on MovaiBaseModel

- dal/classes/protocols/wsredissub.py
- dal/models/role.py
- dal/new_models/__init__.py
- dal/new_models/base.py
- dal/new_models/base_model/common.py
- dal/new_models/base_model/redis_model.py
- dal/new_models/configuration.py
- dal/new_models/flow/flow.py
- dal/new_models/message.py
- dal/new_models/role.py
- dal/new_models/var.py
- dal/tools/backup.py
- dal/tools/migrate_tool.py
- setup.py
[BP-1161](https://movai.atlassian.net/browse/BP-1161) - fix new and init on MovaiBaseModel
[BP-1161]: https://movai.atlassian.net/browse/BP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.9

- .pylintrc
- dal/scopes/fleetrobot.py
- dal/scopes/robot.py
Releasing SPAWNER_BIND_ADDR switch to unix socket (#202)
> Releasing SPAWNER_BIND_ADDR switch to unix socket (#202)

- .bumpversion.cfg
- setup.py
Fix DP-1384 for EE 2.4.1
- based on 2.5.0.6
- #202
> Fix DP-1384 for EE 2.4.1

- .bumpversion.cfg
- dal/helpers/parsers.py
- dal/models/container.py
- dal/models/flow.py
- [BP-1166](https://movai.atlassian.net/browse/BP-1166):
- Merging same commit already added to 2.4 on #201
[BP-1166]: https://movai.atlassian.net/browse/BP-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Apply fix for BP-1166 (subflow default params not applied) on 2.5

- dal/movaidb/database.py
Create a Redis subscriber manager, to keep the state of redis (context keys) subscriptions in memory
> Create a Redis subscriber manager

- dal/classes/protocols/wsredissub.py
close all connections when release is called
> BP-1210 Subscription to changes on redis via ws/subscribe fails silently

- dal/movaidb/database.py
Until we start using the new ioredis library, we are hiding this deprecation warning, which is spammed by each redis communication opened
> BP-890 hide deprecation warning from using a archived aioredis

- dal/classes/protocols/redissub.py
Reverting since this was deemed a bad usability issue
> Revert "Update redissub.py"

- .github/workflows/TestOnPR.yml
- dal/classes/utils/token.py
Same as #235, but for releases/2.5.0
> BP-1237: Small code fix (2.5.0)

- dal/classes/utils/token.py
- dal/models/baseuser.py
- dal/models/model.py
- dal/scopes/fleetrobot.py
Adds functions on the FleetRobot to list robots in the fleet and to remove them.
Also includes other code improvements for issues detected during development. 
Used by https://github.com/MOV-AI/backend/pull/229
Part of [BP-1270](https://movai.atlassian.net/browse/BP-1270)
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~ Tested manually
[^note]:
[BP-1270]: https://movai.atlassian.net/browse/BP-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1270: Remove robots from fleet

- CHANGELOG.md
- dal/utils/callback.py
- pyproject.toml
- [BP-1371](https://movai.atlassian.net/browse/BP-1371): NameError: name 'gd' is not defined
[BP-1371]: https://movai.atlassian.net/browse/BP-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Define _user_functions_class so it can be overwritten

- CHANGELOG.md
- dal/classes/common/singleton.py
- dal/models/configuration.py
- dal/models/flow.py
- pyproject.toml
> Revert "Merge pull request #265 from MOV-AI/improvement/BP-1310-caching"

- CHANGELOG.md
- dal/scopes/robot.py
- dal/validation/schema/1.0/Robot.json
[RP-3269](https://movai.atlassian.net/browse/RP-3269): Have HFM working on the real lab
- Add robot type and robot model to robot class
This PR is needed for https://github.com/MOV-AI/flow-initiator/pull/192
[RP-3269]: https://movai.atlassian.net/browse/RP-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add robot type and model to robot class

- CHANGELOG.md
- dal/models/acl.py
- dal/models/baseuser.py
- dal/models/scopestree.py
- dal/scopes/callback.py
- docs/source/conf.py
- docs/source/index.rst
- docs/source/permissions.rst
- pyproject.toml
- [BP-1312](https://movai.atlassian.net/browse/BP-1312): Validation of ability for non-super user to run callbacks is broken
[BP-1312]: https://movai.atlassian.net/browse/BP-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1312: Operator run callback

- .github/workflows/TestOnPR.yml
- CHANGELOG.md
- dal/models/nodeinst.py
- pyproject.toml
- [BP-1303](https://movai.atlassian.net/browse/BP-1303): Rosparam.get_param() of a disabled parameter returns the value instead of None
[BP-1303]: https://movai.atlassian.net/browse/BP-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Value of disabled parameter on ui is "None"

- .github/workflows/TestOnPR.yml
- CHANGELOG.md
- dal/helpers/parsers.py
- dal/models/container.py
- dal/models/flow.py
- dal/models/nodeinst.py
- pyproject.toml
Same as #290, but for releases/3.1
> BP-1365: Fix subflow param

- CHANGELOG.md
- dal/movaidb/database.py
- dal/tools/backup.py
- pyproject.toml
- tests/unit-docker/data/manifest.txt
- tests/unit-docker/data/metadata/Annotation/delete_me.json
- tests/unit-docker/data/metadata/Callback/delete_me.json
- tests/unit-docker/data/metadata/Configuration/delete_me.json
- tests/unit-docker/data/metadata/Flow/delete_me.json
- tests/unit-docker/data/metadata/GraphicScene/delete_me.json
- tests/unit-docker/data/metadata/Layout/delete_me.json
- tests/unit-docker/data/metadata/Node/delete_me.json
- tests/unit-docker/data/metadata/SharedDataEntry/delete_me_opt0.json
- tests/unit-docker/data/metadata/SharedDataTemplate/delete_me.json
- tests/unit-docker/test_tools_backup.py
- [BP-1420](https://movai.atlassian.net/browse/BP-1420): Initial cleanup on backup tool
[BP-1420]: https://movai.atlassian.net/browse/BP-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cleanup on backup tool

- CHANGELOG.md
- dal/models/callback.py
- pyproject.toml
- Add name to logger
----
How to test:
- install latest platform 2.4.4
- update version of movai-core-shared to `3.1.2.1` in spawner (latest) as root
- build this branch and install it in spawner as root
- run regression tests from https://github.com/MOV-AI/gd-node/pull/135
> BP-1434: Duplicated logs on spawner

- .vscode/extensions.json
- Makefile
- README.md
> Review readme, add Makefile

- CHANGELOG.md
- dal/models/acl.py
- dal/models/role.py
- pyproject.toml
- tests/unit/with_db/test_models_role.py
- [BP-1441](https://movai.atlassian.net/browse/BP-1441): Operator does not have permission to get scene
- **Add graphicscene read permissions**
- **Refactor roles creation, use dict for role resources**
- **Update operator and deployer permissions**
- **Add tests for Role**
[BP-1441]: https://movai.atlassian.net/browse/BP-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1441: Operator permission to get scene

- CHANGELOG.md
- pyproject.toml
- On #311 the version was reverted by mistake
> Fix version number due to PR #311

- CHANGELOG.md
- dal/tools/backup.py
- dal/tools/mobdata.py
- pyproject.toml
- Fix mobdata usage (missing 1 required positional argument: 'args')
- Function specified in pyproject.toml can't have arguments
> Fix mobdata usage

- dal/scopes/scope.py
- dal/scopes/translation.py
- dal/validation/validator.py
- pyproject.toml
Adds a new validator that checks that the imported PO files have a valid format (uses Babel for the validation)
> BP-1462: Validate imported PO files

- CHANGELOG.md
- dal/tools/extract_i18n.py
- pyproject.toml
- tests/unit/tools/test_extract_i18n.py
Standalone script that reads a directory containing .py files, finds all the calls to the logging functions that contain `ui=True`, extracts the string used, and generates a PO file with all those strings, indicating their origin and whether they are regular strings or f-strings.
> BP-1462: Add tool to extract strings into PO file

- dal/tools/backup.py
- tests/unit/data/invalid/manifest.txt
- tests/unit/data/invalid/metadata/Translation/invalid_po.json
- tests/unit/data/invalid/metadata/Translation/invalid_po_pt.po
- tests/unit/with_db/test_scopes.py
- tests/unit/with_db/test_tools_backup.py
> Add tests for po validation

- dal/tools/extract_i18n.py
- tests/unit/tools/test_extract_i18n.py
- tests/unit/validation/test_validator.py
- Fix separator on logs4translation
> Fix separator on logs4translation
