MOV-AI/data-access-layer

dal/scopes/nodeinst.py
the problem was that it was been calculated twice
the first time that it calculated all of the params it was good
then it checked for "property is_node_to_launch"
that checked the param _launch but without the correct context of the
main flow
the fix was that _launch param don't need to be calculated twice or more
once it been calculated, it will never change
see ticket:
https://movai.atlassian.net/browse/BP-556
=> Bugfix/bp 556  launch is not being passed

dal/models/lock.py
bug fix to change behavior
previously when using lock without any parameter lock()
the lock was set forever (without any timeout)
so this commit changes this behavior so that the default will be 90 seconds
meaning lock() is like lock(timeout=90)
to check it:
please go inside the spawner container and run
a = Lock('a')
a.acquire() # print: True
a.inspect() # should see ('f8db180f07a5438bae3180f95fc16daa', []) or something else in the first part
a.inspect() # should see (None, [])
jira:
https://movai.atlassian.net/browse/CSAI-2239
- [x ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
[^note]:
The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template. …
=> Bugfix/csai 2239/lock acquire shouldnt be persistent

dal/data/shared/vault.py
fix secret key initialization to support community edition where there is not movai-serice
jira:
https://movai.atlassian.net/browse/BP-828?atlOrigin=eyJpIjoiMzg4NTFmMzUxMDAzNGJmM2E2MDJlNjI3YWU3ODZmZmEiLCJwIjoiaiJ9
'- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue'
[^note]:
=> update secret key import to support community version

setup.py
- [BP-896](https://movai.atlassian.net/browse/BP-896) dal_backup: command not found on tugbot spawner
[BP-896]: https://movai.atlassian.net/browse/BP-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-896 change backup to dal_backup

dal/movaidb/database.py
- [BP-910](https://movai.atlassian.net/browse/BP-910): Redis subscriber update gives a del event before updating
[BP-910]: https://movai.atlassian.net/browse/BP-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> removed redundant del before set

dal/tools/backup.py
- bump versions
- restore linting configurations files
- fix metadata import tools/backup.py: https://movai.atlassian.net/browse/DP-1047
Now using an ENV var which is set in spawner, backend, health-node to identify if the metadata needs to be installed:
- in a manager : REDIS_MASTER_HOST is set to redis-master (inside container hostname)
- in a fleet member : REDIS_MASTER_HOST is set to haproxy (outside host proxied by haproxy)
```
redis_master_host = os.getenv("REDIS_MASTER_HOST", "None")
if redis_master_host in "redis-master":
redis_write = True
else:
redis_write = False
```
---
=> Fix updating a fleet member firmware overwrite redis-master DB

dal/tools/backup.py
- [BP-1020](https://movai.atlassian.net/browse/BP-1020): Installation of packages inside flow-initiator hang if it was not started as a robot
[BP-1020]: https://movai.atlassian.net/browse/BP-1020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1020 added imports inside functions instead

dal/classes/protocols/wsredissub.py, dal/movaidb/database.py, dal/scopes/fleetrobot.py
- A fix for gd node take long time to kill [BP-1130](https://movai.atlassian.net/browse/%5BDP-1349) [also include another fix from shared](https://github.com/MOV-AI/movai-core-shared/pull/131)
- A fix for closing WSRedisSub is unsubscribing all web sockets [BP-1128](https://movai.atlassian.net/browse/BP-1128)
- [BP-872](https://movai.atlassian.net/browse/BP-872) - convert frontend callback to rest api
[BP-1130]: https://movai.atlassian.net/browse/BP-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1128]: https://movai.atlassian.net/browse/BP-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-872]: https://movai.atlassian.net/browse/BP-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> Ver 2.5.0-6

.bumpversion.cfg, .pylintrc, dal/helpers/parsers.py, dal/models/container.py, dal/models/flow.py, setup.py
Previously if a subflow param was by default pointing  to a flow parameter and there was no value given in the instance, it would give an exception of trying split a NoneType.
In this fix, we are now checking if the default param is pointing to another flow when there is no value on the instance and moving on to check the upper flow. In case it is the main flow, we get the default param.
Test flow to validate fix is included in [BP-1166](https://movai.atlassian.net/browse/BP-1166)
[^note]:
[BP-1166]: …
=> BP-1166 : get default values of subflows when no instance value is set

dal/scopes/fleetrobot.py
- [BP-1194](https://movai.atlassian.net/browse/BP-1194): Flow is started multiple times which leads to weird behavior
- When https://github.com/MOV-AI/data-access-layer/pull/205 was merged, a condition was missed
- Added a few more logs, if you think they are too much just let mw know
The condition `if hasattr(self, "spawner_client")` seems redundant, should it be removed?
[BP-1194]: https://movai.atlassian.net/browse/BP-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't send command to redis if response not required

dal/models/configuration.py
There was an attempt to improve the performance of the yaml.load function by implementing a cache [here](https://github.com/MOV-AI/movai_classes/commit/579f89e9e4ed3fe0fe729708bdb5226d07dd1c58#diff-7acde07cc5cff3653fa6e2e554a2f1abfb70aca5872dcc01328bad253b0b8e7c)
[BP-1195](https://movai.atlassian.net/browse/BP-1195): The cache wasn't working properly because it allowed external entities to edit the cached dictionary - use case of overwritten annotations - and then every time you wanted to access the same configuration you would get the cached dictionary and not the one in the DB. This way didn't save from reading from the DB either, it was actually reading 2 times from the DB lol.
So for now, will remove this caching way and the unnecessary read of DB.
[BP-1195]: …
=> [BP-1195] Overwrite of one annotation in a trajectories seems to affect all trajectories with same annotation

dal/classes/utils/secretkey.py, dal/classes/utils/token.py, dal/movaidb/database.py, dal/plugins/persistence/redis/redis.py, dal/utils/redis_mocks.py
Adds some classes that allow mocking Redis communications. There are two classes:
- FakeAsyncConnection is only used for mocking PUB/SUB messages, specifically the subscription part. It'll open a (local) channel and allow waiting for new messages.
- FakeConnection has two features:
1) Recording and playback of Redis communications, inspired by VCRpy. You set RECORDING=True and then run the test once on a robot with Redis running. It'll monitor the commands and responses to and from Redis, and record them in a pickle file. Afterwards, you can set RECORDING=False, and run the test again: the mock will return the recorded responses that Redis would have sent, without having to actually run Redis.
2) Support for mocking PUB/SUB messages, specifically the publishing part. It communicates with …
=> Redis mocking tool

dal/scopes/fleetrobot.py
DP-1504 is a review of ZMQClient classes in movai-core-shared, this has impact on send_request() prototype which was using a badly written `respose_required` parameter.
This is catch by QA platform tests:
```
FAILED test_platform_tests.py::test_tc_23_test_that_a_flow_parameter_arrives_to_a_gd_node_inside_a_sub_flow - RuntimeError: Failed POST https://localhost:443/api/v1/frontend/ide/ with {'func': 'sendToRobot', 'args': ['S...
FAILED test_platform_tests.py::test_tc_16_test_runtime_parsed_params_fleet_var - RuntimeError: Failed POST https://localhost:443/api/v1/frontend/ide/ with {'func': 'sendToRobot', 'args': ['S...
FAILED test_platform_tests.py::test_tc_14_test_runtime_parsed_params_flow_var - RuntimeError: Failed POST https://localhost:443/api/v1/frontend/ide/ with {'func': …
```
=> Missing renaming for DP-1504

.github/workflows/TestOnPR.yml, dal/classes/utils/token.py
It's just a variable being used when it wasn't yet set (due to an exception).
Ticket: [BP-1237](https://movai.atlassian.net/browse/BP-1237)
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
[^note]:
[BP-1237]: https://movai.atlassian.net/browse/BP-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1237: Fix small code bug

.github/workflows/TestOnPR.yml, dal/classes/protocols/redis.py, dal/movaidb/database.py
By mistake, parts of PR #222 were merged in PR #232. This PR reverts those incorrect merges, while keeping the parts that were correct (the port remapping fix and the Redis mocking tool)
Run the tests on a local sanity robot, the Tugbot worked well.
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
[^note]:
=> Revert CallbackSubscription class

dal/plugins/persistence/redis/redis.py, dal/tools/backup.py
The _REDIS_MASTER_POOL was converted from a class variable to an instance variable, but not all uses in the code where updated. The error in the UI Tests was: `RuntimeError: 500 500: AttributeError: type object 'RedisPlugin' has no attribute '_REDIS_MASTER_POOL'`
Also added explicit connection to Redis on the backup too.
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
[^note]:
=> Fix syntax error

dal/data/tree.py, dal/movaidb/database.py
Adding the `__len__` caused Python to change its behavior when the code tests the truthiness of the object (as in, `if obj:`).
Also cleaning up a warning that was way too verbose.
TIcket: [BP-1259](https://movai.atlassian.net/browse/BP-1259)
[^note]:
[BP-1259]: https://movai.atlassian.net/browse/BP-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1259: Fix bug in GraphicScene API

dal/scopes/node.py, tests/test_node.py
Even if there's no port with a ROS template, as long as there's a
Path set, it should be considered a ROS node, so that the binary
defined in the path can be run.
Also adds unit tests for the Node class. They can be a base for the migration to Pydantic.
Ticket: [BP-1232](https://movai.atlassian.net/browse/BP-1232)
[^note]:
[BP-1232]: https://movai.atlassian.net/browse/BP-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1232: Set correct node type

dal/movaidb/database.py
When an exception was happening when connecting to Redis, it was logged but never re-raised, so the node got stuck in a bad state. This commit re-raises the exception so it can be handled.
Ticket: [BP-1250](https://movai.atlassian.net/browse/BP-1250)
~- [ ] Link to relevant pull requests, esp. upstream and downstream changes~
~- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
[^note]:
[BP-1250]: https://movai.atlassian.net/browse/BP-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> BP-1250: Bubble up connection errors

dal/models/baseuser.py, dal/models/role.py
If a Role has any user assigned to it, an error will be returned when someone tried to delete it.
Tests will be added on the [qa_api_tests](https://github.com/MOV-AI/qa_api_tests/) repository.
Ticket: [BP-1267](https://movai.atlassian.net/browse/BP-1267)
[^note]:
[BP-1267]: https://movai.atlassian.net/browse/BP-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1267: Prevent deleting role with users

dal/helpers/parsers.py, dal/models/configuration.py, dal/models/flow.py, tests/test_flow.py
When a configuration isn't found, an error is supposed to be logged. There was a bug when the missing configuration was a parameter from the Flow and not a Node.
Ticket: [BP-1263](https://movai.atlassian.net/browse/BP-1263)
[^note]:
[BP-1263]: https://movai.atlassian.net/browse/BP-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1263: Fix error when Configuration is not found

CHANGELOG.md, dal/utils/callback.py, pyproject.toml
The loading of enterprise models to callbacks was kept in GD-Node, but that's an error because:
1) Backend callbacks require enterprise models like Metrics, so they need to be available outside of GD-Node
2) movai-core-enterprise doesn't depend on gd-node, so there's no issue in loading it in the DAL
Ticket: [BP-1360](https://movai.atlassian.net/browse/BP-1360)
See also https://github.com/MOV-AI/gd-node/pull/127
[^note]:
[BP-1360]: https://movai.atlassian.net/browse/BP-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> BP-1360: Migrate enterprise model loading to DAL callback

CHANGELOG.md, dal/models/baseuser.py, pyproject.toml
- [BP-1405](https://movai.atlassian.net/browse/BP-1405): Backeng logs an error if someone tries to login with a user that does not exist
[BP-1405]: https://movai.atlassian.net/browse/BP-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change log to info

CHANGELOG.md, dal/helpers/parsers.py, dal/models/container.py, dal/models/flow.py, dal/models/nodeinst.py, pyproject.toml
When trying to get a parameter from a parent flow, there was a bug that set the incorrect context,
due to an incorrect call to get_param()
Ticket: [BP-1365](https://movai.atlassian.net/browse/BP-1365)
Test PR: https://github.com/MOV-AI/movai_qa_platform_tests/pull/160
[^note]:
[BP-1365]: https://movai.atlassian.net/browse/BP-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1365: Fix call to get_param

dal/models/flowlinks.py, dal/movaidb/database.py, tests/unit/test_transitions.py
Adds unit tests that cover the get_node_dependencies and get_node_transitions methods of the Flow class.
Ticket: [BP-1431](https://movai.atlassian.net/browse/BP-1431)
[^note]:
[BP-1431]: https://movai.atlassian.net/browse/BP-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1431: Add tests for node transitions
